### PR TITLE
Integrate header version 3

### PR DESCRIPTION
**Pull request by duranmla**
**What:**
Add the latest version of the organisation header

**Why:**
We want to migrate all our spaces to latest version of the header

**How:**
- Integrate logo version 3
- Shadowing expected assets for latest version of the header in order to load logo properly

**Note:**
After this intention there are a couple things we will improve on the header. Such a:
- [x] Horizontally center the logo when header shrink
- [x] Prevent change vertical height on desktop on scroll

_I will do the changes above before merging this pull request_

### CODE REVIEW

**Review by thiagodemellobueno — CHANGES_REQUESTED** [review]
@duranmla - see the review here:

https://github.com/debtcollective/packages/pull/159#pullrequestreview-677415656

Less critically - there's a flash of unstyled content on load. 
I know this is a bit of an issue with stencil slots.
There are some tips here:
https://bbellmyers.github.io/2020/09/27/fouc-stencil.html
and
https://dev.to/ionic/why-we-use-web-components-2c1i

**Comment by duranmla** [comment]
@thiagodemellobueno the approach to hide while the component is being hydrated it is something we have done already. Isn't? Or I am missing something. Besides, let's try to focus on current intentions and keep iterating. This PR is about the integration of the header. In that sense, I would expect https://github.com/debtcollective/packages/pull/159#pullrequestreview-677415656 to be here. In that way is easier to have context.

In any case good catch. I am able to reproduce the issue in both Chrome and Firefox. I will take a look before merging this as this is a integration flaw.

**Comment by thiagodemellobueno** [comment]
Adding my comments from the header here (since its more an integration thing) 

@duranmla - much of of the time (out of 24 loads it happened 15 times) the nav fails to render over here:
https://deploy-preview-133--tdc-home.netlify.app/
It's happening often enough where it doesnt seem like an edge case.

When loading with a clean cache, it seems to work pretty consistently though. Still this wont be the case for most of our users.

This is the console error:
```
TypeError: NetworkError when attempting to fetch resource. dc-header_4.entry.js:422:20
    e dc-header_4.entry.js:422
    s runtime.js:63
    _invoke runtime.js:293
    $/</< runtime.js:118
    Babel 2
        r
        c
```
Here's the rest of the console output (in case its specifically relevant though this looks like its mostly about the netlify build tem domains?):
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://community-test.debtcollective.org/session/csrf.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://development.debtcollective.org’).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at data:text/plain;base64,Cg==. (Reason: CORS request not http).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at data:text/plain;base64,Cg==. (Reason: CORS request not http).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed).
```
Is there something we can do re: setting a timeout and requesting the assets until some sort of success?

**Comment by thiagodemellobueno** [comment]
@duranmla  - re: flash of usntyled content ,
If we have a solution, its not implemented here? or at least if it were we wouldnt be seeing this?

**Comment by thiagodemellobueno** [comment]
@duranmla  - lets set the header height in CSS here, so if there is a flash, at least it doesnt push the hero down and "jitter" as it loads in.

**Comment by thiagodemellobueno** [comment]
@duranmla  
Sadly still borks on firefox and safari a pretty high percentage of reloads (crtl-shift) 
Screen Shot 2021-06-09 at 4 02 59 PM

Interestingly chrome is feeling pretty solid.

Screen Shot 2021-06-09 at 4 03 49 PM


A series of issues in the console:
```
[Info] Successfuly preconnected to https://cdn.sanity.io/
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
[Error] Failed to load resource: the server responded with a status of 404 () (current.json, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (094bad65c73bfb756442e275bc9c072b, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (bb14f760415d2e1e1cc3d8e45e134439, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (023e60ede3cf160fe60cfe623da8ed27, line 0)
[Warning] The resource https://deploy-preview-133--tdc-home.netlify.app/page-data/index/page-data.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://deploy-preview-133--tdc-home.netlify.app/page-data/sq/d/2007622205.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://deploy-preview-133--tdc-home.netlify.app/page-data/sq/d/2597682244.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://deploy-preview-133--tdc-home.netlify.app/page-data/sq/d/436889252.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://deploy-preview-133--tdc-home.netlify.app/page-data/sq/d/624200592.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://deploy-preview-133--tdc-home.netlify.app/page-data/app-data.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
```

**Review by thiagodemellobueno — CHANGES_REQUESTED** [review]
"Join the Union" link points to `//` which isnt 'absolute' but rather points the browser to that string.
Resulting in `site cant be reached` error.

**Comment by duranmla** [comment]
@thiagodemellobueno yes, the issue not rendering apparently cause CORS _(although in development doesn't happen)_ hasn't been resolved. Nonetheless, I will propose to move forward and merge as I don't see how CORS error will happen on production and I am running out of facts to debug this.

If the error persist we can have another round of check over this same topic. I am pushing new changes to the header and I will update the version and then merge the code if something goes wrong in production I will revert the merge commit

**Comment by thiagodemellobueno** [comment]
@duranmla  - sure sounds good to me, but please do check and fix all the links first!

**Pull request merged**
