### PR TITLE
Header integration version 3.+

### PR DESCRIPTION
**Pull request by duranmla**
**What:**
Add latest version of the header to the page

**Why:**
As a part of the effort needed to unify the navigation experience

**How:**
Use latest published version of the component

**Media:**
https://www.loom.com/share/bca7b98bf25b4550885686134ada25c0

### CODE REVIEW

**Review by thiagodemellobueno — CHANGES_REQUESTED** [review]
Loading consistently, which is great!

Some links seem to be tripping up though:

When I click "Member Login"  it goes to this URL : https://community-test.debtcollective.orgsession/sso_cookies?return_url=https://development.debtcollective.org

Browse events goes to this (missing slash after org)
https://community-test.debtcollective.orgupcoming-events/ 

Many subnav links dont seem to trigger, or issue error.
ALmost feel like they have `prevent default` applied to them on clikc
It seems to be links that lead offsite or to other subdomains.
WHich ones work and dont work seems to behave differently whether you are in the about us page or not (which maybe a hint, but didnt see anything telling in the console)

- Sign the petition
- Email your reps
- All links under For Members
- Learn about debt
- And many others depending on which page you are on (weird?)

We're getting closer though!

**Comment by duranmla** [comment]
Thanks @thiagodemellobueno for this first round of testing.
I will take a look to the links. Other than that, there is nothing we can currently do to allow the member login to work on preview because we don't know the url that netlify will generate. It is clear that technical limitation or should I explain more?

**Comment by duranmla** [comment]
02ef648 has the fix for the issue with external links.
Let me know if you find something else @thiagodemellobueno

**Comment by thiagodemellobueno** [comment]
@duranmla - I don't expect member login to work, but i do expect it to generate a valid URL no?

**Comment by thiagodemellobueno** [comment]
@duranmla  - aaah, i see - lets go ahead and merge it then. 
And test on dev.

**Comment by duranmla** [comment]
Although, I think there is no staging for the homepage.
_Or I am missing some urls?_

**Comment by thiagodemellobueno** [comment]
You are likely to know better than I.
In my understanding we just have 

the netlify preview branches and:
development.debtcollective.org

then merge right to master for "production."

Normally i'd say we dont 'need a specific staging` cause netlify. 
But we have so many integrations (like the stuff in packages) and interdecpendencies that we've seen the consequence of how it affects our ability to test everything together.

**Pull request merged**
