### PR TITLE
Donation widget/storybook improvement

### PR DESCRIPTION
**Pull request by duranmla**
**What:**
Add one story per each component within the widget

**Why:**
It will allow to have a better way to iterate over each piece within the flow

**How:**
Define more stories within the donation widget one where we list:
- Type control
- Payment, Address forms
- Donation once and monthly form

**Media:**
[Showcase stories and overall documentation improvement](https://www.loom.com/share/14f7e821e57c4ae5b81f42577d6a28e4)

### CODE REVIEW

**Comment by orlando** [comment]
@duranmla what about having different stories instead of just one? what are your thoughts on this?

**Review by arathjz — APPROVED** [review]

**Comment by duranmla** [comment]
@orlando initially I was thinking about it. Nevertheless, it was more "hassle" to go over each file to drop a line that is not mean to be touched _(as you edit within the component code)_ besides, I part from the fact that we are dealing with the same composition, which makes the stories somehow related and I can group them into the same "DonationWidget" option.

**IF** I observe in the future this file needs to growth for some reason I will evaluate too separate but for now I see convenient to have it in the same file. Nevertheless, if you feel it has some advantage to do so and prefer to do so we can change it and create multiple stories files.

**Comment by duranmla** [comment]
I will merge... as seems there is nothing blockers so far and there is already one approval.
_If we want to refactor, let me know_

**Pull request merged**
